import unittest
import sys
from ROOT import TFile, TTree, gROOT, gSystem, vector


class TestAMSim(unittest.TestCase):
    """Test the pattern bank generated by PatternGenerator"""

    infile = "patternBank.root"

    def setUp(self):
        gROOT.SetBatch(True)
        gROOT.SetMacroPath(gSystem.Getenv("CMSSW_BASE")+"/src/SLHCL1TrackTriggerSimulations/AMSimulation")
        gROOT.LoadMacro("python/test/loader.h+")
        self.tfile = TFile.Open(self.infile)
        self.ttree = self.tfile.Get("patternBank")
        self.nevents = self.ttree.GetEntries()

    def tearDown(self):
        pass

    def test_nevents(self):
        self.assertEqual(self.nevents, 63 + 15 * 7 + 0 * 28)

    def test_superstripIds(self):
        tree = self.ttree
        for ievt in tree:
            l = 0
            for ssId in ievt.superstripIds:
                if l<6:
                    self.assertNotEqual(ssId, 0)
                else:
                    self.assertEqual(ssId, 0)
                l += 1

            self.assertTrue(ievt.superstripIds.size() == 8)

    def test_frequency(self):
        tree = self.ttree
        for ievt in tree:
            self.assertEqual(ord(ievt.frequency), 1)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        TestAMSim.infile = sys.argv.pop()

    unittest.main()
