import FWCore.ParameterSet.Config as cms

## 2015 + new phase 1 pixel detector + Tracker BarrelEndcapv(described as a pixel detector before the detid migration)

XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring('Geometry/CMSCommonData/data/materials.xml',
        'Geometry/CMSCommonData/data/rotations.xml',
        'Geometry/CMSCommonData/data/extend/cmsextent.xml',
        'Geometry/CMSCommonData/data/PhaseI/cms.xml',
        'Geometry/CMSCommonData/data/cmsMother.xml',
        'Geometry/CMSCommonData/data/cmsTracker.xml',
        #'Geometry/CMSCommonData/data/caloBase.xml',
        #'Geometry/CMSCommonData/data/cmsCalo.xml',
        #'Geometry/CMSCommonData/data/muonBase.xml',
        #'Geometry/CMSCommonData/data/cmsMuon.xml',
        'Geometry/CMSCommonData/data/mgnt.xml',
        'Geometry/CMSCommonData/data/PhaseI/beampipe.xml',
        'Geometry/CMSCommonData/data/cmsBeam.xml',
        #'Geometry/CMSCommonData/data/muonMB.xml',
        #'Geometry/CMSCommonData/data/muonMagnet.xml',
        'Geometry/CMSCommonData/data/cavern.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdMaterials.xml',
        'Geometry/TrackerCommonData/data/pixfwdCommon.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdCylinder.xml', 
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/pixfwd.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdDisks.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdInnerDisk1.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdInnerDisk2.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdInnerDisk3.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdOuterDisk1.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdOuterDisk2.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdOuterDisk3.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdblade1.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdblade2.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixfwdblade3.xml',
        'Geometry/TrackerCommonData/data/PhaseI/pixbarmaterial.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladder.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull0.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull1.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull2.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarladderfull3.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer0.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer1.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer2.xml', 
        'Geometry/TrackerCommonData/data/PhaseI/pixbarlayer3.xml', 
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/pixbar.xml', 
        'Geometry/TrackerCommonData/data/trackermaterial.xml',
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/tracker.xml',
        'Geometry/TrackerCommonData/data/trackerpixbar.xml',
        'Geometry/TrackerCommonData/data/PhaseI/trackerpixfwd.xml',
        'Geometry/TrackerCommonData/data/PhaseII/BarrelEndcap5D/trackerStructureTopology.xml',
        'Geometry/TrackerSimData/data/PhaseII/BarrelEndcap5D/trackersens.xml',
        'Geometry/TrackerRecoData/data/PhaseII/BarrelEndcap5D/trackerRecoMaterial.xml',
        'Geometry/TrackerSimData/data/PhaseII/BarrelEndcap5D/trackerProdCuts.xml',
        'Geometry/TrackerSimData/data/trackerProdCutsBEAM.xml',
        'Geometry/CMSCommonData/data/FieldParameters.xml'),
    rootNodeName = cms.string('cms:OCMS')
)


